* TODO edit the unemployment statement
** what I sent LC for peer review
The Covid crisis has left millions of Colombians without work, and devastated the incomes of millions more.

Even the raw unemployment data is unprecedented. Excluding 2020, the highest unemployment level in the last ten years was 13.56% (in January 2011), and its highest level this century was 17.87 (in January 2002). This May it registered 21.4%.

And conditions now are worse than those numbers suggest, because unemployment figures only count people actively looking for work. The current crisis is unique in that whole industries -- restaurants, live sports, movie theaters, office maintenance, babysitting -- have nearly vanished. The unemployment data omits Colombians who ordinarily work but have given up on finding a job during the pandemic. If we were to count the sudden, massive increase since January in "inactivos" -- workers who are neither working nor looking for work -- as additional unemployed people, the May unemployment rate would be 31% (and the April rate, 34%)[footnote]. These figures are without modern precedent.

[footnote] Since 2010 the fraction of workers who are "inactivo" -- neither working nor looking for work -- has stayed in a tight band between 34% and 38%. In January it was 37%. In April it peaked at 48%, and in May it fell to 45%.

It seems plausible that the massive increase in "inactivos" between January and May consists of workers who lost their job and knew they could not find another one under present conditions. Per DANE, in January 2020 the number of ocupados, desocupados and inactivos in Colombia were 22.356, 2.655 and 14.602 million respectively, and in May they were 17.361, 4.670 and 17.733 million. Those figures imply an increase in inactivos of 17.733 - 14.602 = 3.13 million, and an official unemployment rate in May of 4.670 / (4.670 + 17.361) = 21.2%. If those 3.13 million newly inactive workers are all "discouraged workers", and we count them instead as part of the unemployed, we find an effective unemployment rate of 7.8 / (7.8 + 17.361) = 31%.

In April the number of employed, unemployed and inactive were 16.430, 4.080 and 19.294 million respectively. A similar analysis comparing January to April leads to an effective unemployment rate of 34.8% in April.
* edits I made on July 2
** TODO send outside of dpocument
*** The first "nota al pie" has no label (it should be labeled "i").
*** I changed "La muestra de la ENPH es muy importante"
 to "La muestra de la ENPH es grande". What I mean to say is that there are a lot of people in it.
** made these edits
*** Las cuentas son sencillas: si un hogar ahorra cero o pocos pesos durante un mes, nunca podrá ahorrar suficiente dinero para un mes de gastos. Puesto de otra forma, el número de meses que un hogar necesita para ahorrar lo necesario para un mes es “gasto/ahorro”.
  "cero o pocos" should be "cero o menos". (Right? I want to say "0 or less than 0".) "Puesto de otra forma" doesn't really work, because that sentence isi not restating the one that came before.
*** reorder
**** this
  El “ingreso corriente monetario disponible” representa el ingreso usual de dinero en efectivo a un hogar después de las deducciones automáticas. “Usual” quiere decir que excluye ingresos por eventos excepcionales, como la venta de un vehículo. Por otra parte, el “efectivo” es el opuesto al ingreso en especie –por ejemplo, si el empleador provee la alimentación, que cuenta como ingreso, pero no como un ingreso en efectivo–.  Las deducciones automáticas incluyen cosas como las contribuciones a pensión y seguridad social.
**** to this
  El “ingreso corriente monetario disponible” representa el ingreso usual de dinero en efectivo a un hogar después de las deducciones automáticas, como las contribuciones a pensión y seguridad social. “Usual” quiere decir que excluye ingresos por eventos excepcionales, como la venta de un vehículo. Por otra parte, el “efectivo” es el opuesto al ingreso en especie –por ejemplo, si el empleador provee la alimentación, que cuenta como ingreso, pero no como un ingreso en efectivo–. 
*** meant to say sample is big, not important
  "La muestra de la ENPH es muy importante."
  It is important, but that's not what I wanted to say -- I wanted to say that it includes an enormous number of people.
*** estos hogares ganan mucho más dinero del que gastan
  should be capitalized
*** TODO making edits
*** pesos mensuales si esto parece
  should be "pesos mensuales. Si esto parece"
