def folder(year):
  if year == 2007: "data/enig-2007"
  elif year == 2017: "data/enig-2017"
  else: error (year + " is not one of the survey years.")

files = {2017:
         [ "coicop.dta"
           , "factores_ciclo19.dta"
           , "hogares_tot_completos.dta"
           , "st2_sea_enc_gcar_csv.dta"
           , "st2_sea_enc_gcau_csv.dta"
           , "st2_sea_enc_gcfhr_ce_csv.dta"
           , "st2_sea_enc_gcfhr_csv.dta"
           , "st2_sea_enc_gcfhu_diarios_csv.dta"
           , "st2_sea_enc_gcfhup_diarios_csv.dta"
           , "st2_sea_enc_gdr_csv.dta"
           , "st2_sea_enc_gdrj1_csv.dta"
           , "st2_sea_enc_gdsr_mer_csv.dta"
           , "st2_sea_enc_gdsu_mer_csv.dta"
           , "st2_sea_enc_gmf_csv.dta"
           , "st2_sea_enc_gmf_transpuesta.dta"
           , "st2_sea_enc_gsdp_dia_csv.dta"
           , "st2_sea_enc_gsdp_diarios_csv.dta"
           , "st2_sea_enc_gsdu_dia_csv.dta"
           , "st2_sea_enc_gsdu_diarios_csv.dta" # the biggest, 1.5GB; if this goes through, everything does
           , "st2_sea_enc_hogc3_csv.dta"
           , "st2_sea_enc_hog_csv.dta"
           , "st2_sea_enc_per_csv.dta"
         ],

         2007: [ "Ig_gsdp_dias_sem.txt"
                 , "Ig_gsdp_gas_dia.txt"
                 , "Ig_gsdp_perceptores.txt"
                 , "Ig_gsdu_caract_alim.txt"
                 , "Ig_gsdu_dias_sem.txt"
                 , "Ig_gsdu_gas_dia.txt"
                 , "Ig_gsdu_gasto_alimentos_cap_c.txt"
                 , "Ig_gsdu_mercado.txt"
                 , "Ig_gs_hogar.txt"
                 , "Ig_gsmf_compra.txt"
                 , "Ig_gsmf_forma_adqui.txt"
                 , "Ig_gsmf_serv_pub.txt"
                 , "Ig_gssr_caract_alim.txt"
                 , "Ig_gssr_gas_sem.txt"
                 , "Ig_gssr_gasto_alimentos_cap_c.txt"
                 , "Ig_gssr_mercado.txt"
                 , "Ig_gs_vivienda.txt"
                 , "Ig_ml_desocupado.txt"
                 , "Ig_ml_hogar.txt"
                 , "Ig_ml_inactivo.txt"
                 , "Ig_ml_ocupado.txt"
                 , "Ig_ml_pblcion_edad_trbjar.txt"
                 , "Ig_ml_persona.txt"
                 , "Ig_ml_vivienda.txt"
         ] }
