* missing
** nh_cgpucfh_p1_s2 : ignore?
** carac. general.
*** cuadernillo 1, page 19: what questions are the last answers on the page for?
* emailed, awaiting
** nc2_cc_p1 = 25 broad categories. vat rates?

** DIRECTORIO
** SECUENCIA_ENCUESTA
** SECUENCIA_P
** CAP
** TODO NC2R_CE_P8 : frequency
*** it would be nice to be sure that frequency and value are orthogonal -- that is, value is the value per purchase, not the total spent on that good last week
** what does this kind of legend mean? "8 » 13
** NH_CGDUCFH_P4 : where gotten, even if not bought
*** TODO ? how to read the legend
*** restaurant, bar, cafeteria: no VAT. otherwise ignore. not quite right -- guys selling on street, for example
** TODO NH_CGDUCFH_P6 : frequency
*** ? how to read legend. 2.1 appears in it, but 2 and not 2.1 appears in the data.
** TODO NH_CGDU_P3 & following ? unit of measure
*** Hopefully we can ignore, but can we? 
*** Do we only need to know price, quantity and frequency?
*** Is it relevant that this is not in every data set?
