* news
* yet to ask
* probably redundant
** bars, cafeterias, restaurants: no VAT. otherwise yes. all four of those "fuera" files are in play.
** nh_cgpucfh_p1_s2 : ignore? (We've already got a COICOP; I don't know what other information this variable could provide. But I can't find a description of it, so I can't rule out the possibility that it's important.)
** pension contributions: There are a number of variables (at least 5) about pensions in 'caracteristicas generales'. Do the other income variables already incorporate it, or is it a part of income we would not be coutning if we didn't use the pension contribution variable?
** nc2_cc_p1 = 25 broad categories. vat rates?
** DONE NC2R_CE_P8 : frequency. yes, it's orthogonal to value.
** NH_CGDUCFH_P4 : where gotten, even if not bought
*** TODO david : how to read the legend
*** restaurant, bar, cafeteria: no VAT. otherwise ignore. not quite right -- guys selling on street, for example
** TODO NH_CGDUCFH_P6 : frequency
*** ? how to read legend. 2.1 appears in it, but 2 and not 2.1 appears in the data.
* meh
** outliers
*** household-member: rural_semanal and urban_diario both reach at least to 82
