* news
* yet to ask
* asking
** Is there a good default frequency to use?
*** the question
Below, for the 1/100 sample, I've gone through each file origin and indicated the number of "weight" observations (because that's never missing) and the number of "freq" observations. Notice that for some kinds of files, freq is very missing. If there was a reasonable defautl frequency to use for those files, we could avoid throwing out a lot of observations (in total, 1 in 14 is missing a frequency value).

I thought maybe the default for "menos frecuentes - articulos" would be yearly, and for the "semanal" files, weekly, and the "diaro" files, daily -- but that's based on very little information ...

*** the data supporting it
articulos
weight         21109
freq           20209

urban capitulo c
weight         3606
freq           3606

rural capitulo c
weight         459
freq           459

rural_personal
weight         48
freq           48

rural_personal_fuera
weight         14
freq            9

rural_semanal
weight         858
freq           731

rural_semanal_fuera
weight         42
freq           40

urban_diario
weight         33302
freq           32059

urban_diario_fuera
weight         5040
freq           3928

urban_diario_personal
weight         5249
freq           4984

urban_personal_fuera
weight         4760
freq           3922

*** how I generated that data
df = data.purchases[ ["weight","freq","file-origin"] ]
for fo in df["file-origin"].unique():
  print( "\n" + fo )
  print( df[ df["file-origin"]==fo] .count() )
* probably redundant
** bars, cafeterias, restaurants: no VAT. otherwise yes. all four of those "fuera" files are in play.
** nh_cgpucfh_p1_s2 : ignore? (We've already got a COICOP; I don't know what other information this variable could provide. But I can't find a description of it, so I can't rule out the possibility that it's important.)
** pension contributions: There are a number of variables (at least 5) about pensions in 'caracteristicas generales'. Do the other income variables already incorporate it, or is it a part of income we would not be coutning if we didn't use the pension contribution variable?
** nc2_cc_p1 = 25 broad categories. vat rates?
** DONE NC2R_CE_P8 : frequency. yes, it's orthogonal to value.
** NH_CGDUCFH_P4 : where gotten, even if not bought
*** TODO david : how to read the legend
*** restaurant, bar, cafeteria: no VAT. otherwise ignore. not quite right -- guys selling on street, for example
** TODO NH_CGDUCFH_P6 : frequency
*** ? how to read legend. 2.1 appears in it, but 2 and not 2.1 appears in the data.
* meh
** outliers
*** household-member: rural_semanal and urban_diario both reach at least to 82
