# PITFALL: The idiom here is the following:
#   .no_younger_than/x:
#     x
#     .no_younger_than/y
#     .no_younger_than/z
#          install -D ...
# That is, in the recipe for `.no_younger_than/x`, every file imported by `x`
# is itself prefixed with `exists`; only `x` itself leaves the prefix out.
# That is what permits recursion.

# TODO The idiom here seems to accomplish everything this does,
# and requires no `.no_younger_than/` folder:
# https://github.com/JeffreyBenjaminBrown/makefile-import-aware/blob/55b285f645d6b336183988db9917816f8883a173/maybe-equally-good/Makefile

.no_younger_than/python/email.py: \
  python/email.py                 \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/email.py

.no_younger_than/python/requests/defs.py: \
  python/requests/defs.py                 \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/requests/defs.py

.no_younger_than/python/requests/lib.py:   \
  python/requests/lib.py                   \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/my_subproc.py
	install -D /dev/null .no_younger_than/python/requests/lib.py

.no_younger_than/python/requests/main.py:      \
  python/requests/main.py		       \
  .no_younger_than/python/common/common.py     \
  .no_younger_than/python/common/my_subproc.py \
  .no_younger_than/python/email.py             \
  .no_younger_than/python/requests/defs.py     \
  .no_younger_than/python/requests/lib.py
	install -D /dev/null .no_younger_than/python/requests/main.py

.no_younger_than/python/requests/test.py:	\
  python/requests/test.py			\
  .no_younger_than/python/common/common.py	\
  .no_younger_than/python/requests/lib.py
	install -D /dev/null .no_younger_than/python/requests/test.py

.no_younger_than/python/tax-proposals-2020/07_22_code_First.py: \
  python/tax-proposals-2020/07-22/code/First.py
	install -D /dev/null .no_younger_than/python/tax-proposals-2020/07_22_code_First.py

.no_younger_than/python/tax-proposals-2020/08_21_main.py:	\
  python/tax-proposals-2020/08-21/main.py			\
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/tax-proposals-2020/08_21_main.py

.no_younger_than/python/tax-proposals-2020/08_21_build.py:	\
  python/tax-proposals-2020/08-21/build.py			\
  .no_younger_than/python/build/output_io.py			\
  .no_younger_than/python/common/common.py			\
  .no_younger_than/python/common/misc.py			\
  .no_younger_than/python/common/describe.py			\
  .no_younger_than/python/draw/util.py
	install -D /dev/null .no_younger_than/python/tax-proposals-2020/08_21_build.py

.no_younger_than/users/$(user)/config/marginal_rates/ocasional_high.py: \
  users/$(user)/config/marginal_rates/ocasional_high.py			\
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/csv_dynamic/r2019/ocasional_high.py

.no_younger_than/users/$(user)/config/marginal_rates/most.py: \
  users/$(user)/config/marginal_rates/most.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/csv_dynamic/r2019/most.py

.no_younger_than/users/$(user)/config/marginal_rates/ocasional_low.py: \
  users/$(user)/config/marginal_rates/ocasional_low.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/csv_dynamic/r2019/ocasional_low.py

.no_younger_than/python/build/ss/functions_test.py: \
  python/build/ss/functions_test.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/ss/functions.py \
  .no_younger_than/python/build/ss/schedules.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/ss/functions_test.py

.no_younger_than/python/build/buildings_test.py: \
  python/build/buildings_test.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/classes.py
	install -D /dev/null .no_younger_than/python/build/buildings_test.py

.no_younger_than/python/build/households_2_purchases.py: \
  python/build/households_2_purchases.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/households_2_purchases.py

.no_younger_than/python/build/households_2_purchases_test.py: \
  python/build/households_2_purchases_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/households_2_purchases_test.py

.no_younger_than/python/build/output_io.py: \
  python/build/output_io.py
	install -D /dev/null .no_younger_than/python/build/output_io.py

.no_younger_than/python/build/vat_rates_test.py: \
  python/build/vat_rates_test.py                 \
  .no_younger_than/python/build/output_io.py     \
  .no_younger_than/python/common/common.py       \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/vat_rates_test.py

.no_younger_than/python/build/buildings.py: \
  python/build/buildings.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/build/buildings.py

.no_younger_than/python/build/purchases/articulos.py: \
  python/build/purchases/articulos.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/purchases/articulos.py

.no_younger_than/python/build/purchases/input_test.py: \
  python/build/purchases/input_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/purchases/articulos.py \
  .no_younger_than/python/build/purchases/capitulo_c.py \
  .no_younger_than/python/build/purchases/nice_purchases.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/purchases/input_test.py

.no_younger_than/python/build/purchases/correct_defs.py: \
  python/build/purchases/correct_defs.py
	install -D /dev/null .no_younger_than/python/build/purchases/correct_defs.py

.no_younger_than/python/build/purchases/correct.py: \
  python/build/purchases/correct.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/purchases/correct_defs.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/build/purchases/nice_purchases.py \
  .no_younger_than/python/build/purchases/articulos.py \
  .no_younger_than/python/build/purchases/capitulo_c.py
	install -D /dev/null .no_younger_than/python/build/purchases/correct.py

.no_younger_than/python/build/purchases/legends.py: \
  python/build/purchases/legends.py
	install -D /dev/null .no_younger_than/python/build/purchases/legends.py

.no_younger_than/python/build/purchases/correct_test.py: \
  python/build/purchases/correct_test.py \
  .no_younger_than/python/build/purchases/correct_defs.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/purchases/correct_test.py

.no_younger_than/python/build/purchases/nice_purchases.py: \
  python/build/purchases/nice_purchases.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/purchases/nice_purchases.py

.no_younger_than/python/build/purchases/collect.py: \
  python/build/purchases/collect.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/purchases/nice_purchases.py \
  .no_younger_than/python/build/purchases/articulos.py \
  .no_younger_than/python/build/purchases/capitulo_c.py
	install -D /dev/null .no_younger_than/python/build/purchases/collect.py

.no_younger_than/python/build/purchases/medios.py: \
  python/build/purchases/medios.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/purchases/medios.py

.no_younger_than/python/build/purchases/capitulo_c.py: \
  python/build/purchases/capitulo_c.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/purchases/capitulo_c.py

.no_younger_than/python/build/people_3_income_taxish_test.py: \
  python/build/people_3_income_taxish_test.py \
  .no_younger_than/python/build/people_3_income_taxish_functions.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/people_3_income_taxish_test.py

.no_younger_than/python/build/households_1_agg_plus.py: \
  python/build/households_1_agg_plus.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/describe.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/people/files.py \
  .no_younger_than/python/build/households_1_agg_plus_defs.py
	install -D /dev/null .no_younger_than/python/build/households_1_agg_plus.py

.no_younger_than/python/build/classes.py: \
  python/build/classes.py
	install -D /dev/null .no_younger_than/python/build/classes.py

.no_younger_than/python/common/fuzz.py: \
  python/common/fuzz.py
	install -D /dev/null .no_younger_than/python/common/fuzz.py

.no_younger_than/python/build/people/empleados.py: \
  python/build/people/empleados.py
	install -D /dev/null .no_younger_than/python/build/people/empleados.py

.no_younger_than/python/build/people/main.py:       \
  python/build/people/main.py                       \
  .no_younger_than/python/build/classes.py          \
  .no_younger_than/python/build/output_io.py        \
  .no_younger_than/python/build/people/empleados.py \
  .no_younger_than/python/build/people/files.py     \
  .no_younger_than/python/build/people/main_defs.py \
  .no_younger_than/python/common/common.py          \
  .no_younger_than/python/common/fuzz.py            \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/people/main.py

.no_younger_than/python/build/people/main_test.py: \
  python/build/people/main_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/people/files.py \
  .no_younger_than/python/build/people/main_defs.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/people/main_test.py

.no_younger_than/python/build/people/files.py: \
  python/build/people/files.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/build/classes.py
	install -D /dev/null .no_younger_than/python/build/people/files.py

.no_younger_than/python/build/people/main_defs.py: \
  python/build/people/main_defs.py
	install -D /dev/null .no_younger_than/python/build/people/main_defs.py

.no_younger_than/python/build/people/collect.py: \
  python/build/people/collect.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/people/files.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/people/collect.py

.no_younger_than/python/build/rate_input_test.py: \
  python/build/rate_input_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/rate_input_test.py

.no_younger_than/python/build/people_2_buildings.py: \
  python/build/people_2_buildings.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/people_2_buildings.py

.no_younger_than/python/build/households_1_agg_plus_defs.py: \
  python/build/households_1_agg_plus_defs.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/regime/r2016.py \
  .no_younger_than/python/regime/r2018.py \
  .no_younger_than/python/regime/r2019.py
	install -D /dev/null .no_younger_than/python/build/households_1_agg_plus_defs.py

.no_younger_than/python/build/ss/functions.py: \
  python/build/ss/functions.py \
  .no_younger_than/python/build/ss/schedules.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/ss/functions.py

.no_younger_than/python/build/purchases_2_vat_test.py: \
  python/build/purchases_2_vat_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/purchases_2_vat_test.py

.no_younger_than/python/report/tests.py:     \
  python/report/tests.py                     \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/report/defs.py
	install -D /dev/null .no_younger_than/python/report/tests.py

.no_younger_than/python/build/households_1_agg_plus_test.py: \
  python/build/households_1_agg_plus_test.py \
  .no_younger_than/python/build/households_1_agg_plus_defs.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/people/files.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/classes.py
	install -D /dev/null .no_younger_than/python/build/households_1_agg_plus_test.py

.no_younger_than/python/build/purchase_sums.py: \
  python/build/purchase_sums.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/purchase_sums.py

.no_younger_than/python/build/purchase_sums_test.py: \
  python/build/purchase_sums_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/purchase_sums_test.py

.no_younger_than/python/build/purchases_2_vat.py: \
  python/build/purchases_2_vat.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/purchases/legends.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/purchases_2_vat.py

.no_younger_than/python/build/ss/schedules.py:	\
  python/build/ss/schedules.py			\
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/build/ss/schedules.py

.no_younger_than/python/build/ss/schedules_test.py: \
  python/build/ss/schedules_test.py                 \
  .no_younger_than/python/build/ss/schedules.py     \
  .no_younger_than/python/common/misc.py            \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/ss/schedules_test.py

.no_younger_than/python/build/classes_test.py: \
  python/build/classes_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/build/classes_test.py

.no_younger_than/python/build/people_3_income_taxish.py: \
  python/build/people_3_income_taxish.py \
  .no_younger_than/python/build/ss/functions.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/people_3_income_taxish_functions.py \
  .no_younger_than/python/regime/r2016.py \
  .no_younger_than/python/regime/r2018.py \
  .no_younger_than/python/regime/r2019.py
	install -D /dev/null .no_younger_than/python/build/people_3_income_taxish.py

.no_younger_than/python/build/people_4_post_households.py:       \
  python/build/people_4_post_households.py                       \
  .no_younger_than/python/common/util.py                         \
  .no_younger_than/python/common/common.py                       \
  .no_younger_than/python/build/people_4_post_households_defs.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/build/people_4_post_households.py

.no_younger_than/python/build/people_4_post_households_test.py:  \
  python/build/people_4_post_households_test.py                  \
  .no_younger_than/python/common/misc.py			 \
  .no_younger_than/python/common/common.py			 \
  .no_younger_than/python/build/people_4_post_households_defs.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/build/people_4_post_households_test.py

.no_younger_than/python/build/people_4_post_households_defs.py: \
  python/build/people_4_post_households_defs.py
	install -D /dev/null .no_younger_than/python/build/people_4_post_households_defs.py

.no_younger_than/python/build/datafiles.py: \
  python/build/datafiles.py
	install -D /dev/null .no_younger_than/python/build/datafiles.py

.no_younger_than/python/build/people_2_buildings_test.py: \
  python/build/people_2_buildings_test.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py
	install -D /dev/null .no_younger_than/python/build/people_2_buildings_test.py

.no_younger_than/python/build/vat_rates.py:  \
  python/build/vat_rates.py                  \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py   \
  .no_younger_than/python/common/misc.py     \
  .no_younger_than/python/common/terms.py
	install -D /dev/null .no_younger_than/python/build/vat_rates.py

.no_younger_than/python/build/people_3_income_taxish_functions.py: \
  python/build/people_3_income_taxish_functions.py
	install -D /dev/null .no_younger_than/python/build/people_3_income_taxish_functions.py

.no_younger_than/python/convert_key_output_for_stata.py: \
  python/convert-key-output-for-stata.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/convert_key_output_for_stata.py

.no_younger_than/python/draw/util.py: \
  python/draw/util.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/draw/util.py

.no_younger_than/python/draw/shell-load.py: \
  python/draw/shell-load.py
	install -D /dev/null .no_younger_than/python/draw/shell-load.py

.no_younger_than/python/draw/examples.py: \
  python/draw/examples.py \
  .no_younger_than/python/draw/util.py
	install -D /dev/null .no_younger_than/python/draw/examples.py

.no_younger_than/python/draw/jupyter-load.py: \
  python/draw/jupyter-load.py
	install -D /dev/null .no_younger_than/python/draw/jupyter-load.py

.no_younger_than/python/regime/cedula_general_gravable.py: \
  python/regime/cedula_general_gravable.py                 \
  .no_younger_than/python/common/misc.py                   \
  .no_younger_than/python/common/common.py                 \
  .no_younger_than/python/common/terms.py
	install -D /dev/null .no_younger_than/python/regime/cedula_general_gravable.py

.no_younger_than/python/regime/test.py:      \
  python/regime/test.py                      \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py   \
  .no_younger_than/python/common/misc.py     \
  .no_younger_than/python/regime/cedula_general_gravable.py
	install -D /dev/null .no_younger_than/python/regime/test.py

# PITFALL: This violates the usual rule that every dependency but the first
# is in .no_younger_than/. That's because they are not (in general)
# part of the repo, but rather generated from a user's .csv config files.
# TODO ? That difference is confusing; can it be smoothed over?
.no_younger_than/python/regime/r2019.py:                    \
  python/regime/r2019.py                                    \
  .no_younger_than/python/common/common.py                  \
  .no_younger_than/python/common/misc.py                    \
  .no_younger_than/python/common/terms.py                   \
  .no_younger_than/python/regime/cedula_general_gravable.py \
  users/$(user)/config/marginal_rates/dividend.py           \
  users/$(user)/config/marginal_rates/most.py               \
  users/$(user)/config/marginal_rates/ocasional_high.py     \
  users/$(user)/config/marginal_rates/ocasional_low.py
	install -D /dev/null .no_younger_than/python/regime/r2019.py

.no_younger_than/python/regime/r2018.py: \
  python/regime/r2018.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/regime/r2018.py

.no_younger_than/python/regime/r2016.py: \
  python/regime/r2016.py \
  .no_younger_than/python/common/misc.py
	install -D /dev/null .no_younger_than/python/regime/r2016.py

.no_younger_than/python/regime/r2018_test.py: \
  python/regime/r2018_test.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/regime/r2018.py
	install -D /dev/null .no_younger_than/python/regime/r2018_test.py

.no_younger_than/python/common/misc.py: \
  python/common/misc.py \
  .no_younger_than/python/build/classes.py
	install -D /dev/null .no_younger_than/python/common/misc.py

.no_younger_than/python/common/util.py: \
  python/common/util.py
	install -D /dev/null .no_younger_than/python/common/util.py

.no_younger_than/python/common/util_test.py: \
  python/common/util_test.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/common/util_test.py

.no_younger_than/python/common/misc_test.py: \
  python/common/misc_test.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/common/misc.py \
  .no_younger_than/python/build/output_io.py
	install -D /dev/null .no_younger_than/python/common/misc_test.py

.no_younger_than/python/common/terms.py: \
  python/common/terms.py
	install -D /dev/null .no_younger_than/python/common/terms.py

.no_younger_than/python/common/describe.py: \
  python/common/describe.py
	install -D /dev/null .no_younger_than/python/common/describe.py

.no_younger_than/python/common/common.py:  \
  python/common/common.py                  \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/terms.py
	install -D /dev/null .no_younger_than/python/common/common.py

.no_younger_than/python/common/my_subproc.py: \
  python/common/my_subproc.py                 \
  .no_younger_than/python/common/common.py
	install -D /dev/null .no_younger_than/python/common/my_subproc.py

.no_younger_than/python/report/pics/people.py: \
  python/report/pics/people.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/draw/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/common.py
	install -D /dev/null .no_younger_than/python/report/pics/people.py

.no_younger_than/python/report/pics/households.py: \
  python/report/pics/households.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/draw/util.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/build/common.py
	install -D /dev/null .no_younger_than/python/report/pics/households.py

.no_younger_than/python/report/pics/purchases.py: \
  python/report/pics/purchases.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/draw/util.py \
  .no_younger_than/python/build/common.py
	install -D /dev/null .no_younger_than/python/report/pics/purchases.py

.no_younger_than/python/report/time_to_save_for_a_month_main.py: \
  python/report/time_to_save_for_a_month/main.py \
  .no_younger_than/python/build/classes.py \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/util.py \
  .no_younger_than/python/common/describe.py \
  .no_younger_than/python/report/time_to_save_for_a_month_defs.py
	install -D /dev/null .no_younger_than/python/report/time_to_save_for_a_month_main.py

.no_younger_than/python/report/time_to_save_for_a_month_explore.py: \
  python/report/time_to_save_for_a_month/explore.py
	install -D /dev/null .no_younger_than/python/report/time_to_save_for_a_month_explore.py

.no_younger_than/python/report/time_to_save_for_a_month_defs.py: \
  python/report/time_to_save_for_a_month/defs.py
	install -D /dev/null .no_younger_than/python/report/time_to_save_for_a_month_defs.py

.no_younger_than/python/report/defs.py:    \
  python/report/defs.py                    \
  .no_younger_than/python/common/common.py \
  .no_younger_than/python/regime/r2016.py  \
  .no_younger_than/python/regime/r2018.py  \
  .no_younger_than/python/regime/r2019.py
	install -D /dev/null .no_younger_than/python/report/defs.py

.no_younger_than/python/report/compare.py:   \
  python/report/compare.py                   \
  .no_younger_than/python/build/output_io.py \
  .no_younger_than/python/common/common.py   \
  .no_younger_than/python/common/terms.py    \
  .no_younger_than/python/draw/util.py       \
  .no_younger_than/python/report/defs.py
	install -D /dev/null .no_younger_than/python/report/compare.py

.no_younger_than/python/report/var_summaries_by_group.py: \
  python/report/var_summaries_by_group.py                 \
  .no_younger_than/python/build/output_io.py              \
  .no_younger_than/python/common/common.py                \
  .no_younger_than/python/common/describe.py              \
  .no_younger_than/python/common/misc.py                  \
  .no_younger_than/python/draw/util.py                    \
  .no_younger_than/python/report/defs.py
	install -D /dev/null .no_younger_than/python/report/var_summaries_by_group.py

.no_younger_than/python/subsample.py: \
  python/subsample.py \
  .no_younger_than/python/build/datafiles.py
	install -D /dev/null .no_younger_than/python/subsample.py

.no_younger_than/haskell/MarginalTaxRates.hs: \
  haskell/MarginalTaxRates.hs
	install -D /dev/null .no_younger_than/haskell/MarginalTaxRates.hs

.no_younger_than/haskell/Main.hs: \
  haskell/Main.hs \
  .no_younger_than/haskell/MarginalTaxRates.hs
	install -D /dev/null .no_younger_than/haskell/Main.hs
