# Without this, the shell history would not be very useful,
# since the configuration file is edited frequently.
show_config:
	cat $(config_file)

# TODO : Dead. Fix or delete.
lag:
	bash bash/report_households_lag.sh $(config_file)

# TODO : Dead. Fix or delete.
diff:
	$(python_from_here) python/test/report_households_diff.py \
          $(config_file)

# Some of these are defined in config_file.
# Others are derived therefrom.
show_params:
	echo "config_file: "           -$(config_file)-
	echo "subsample: "             -$(subsample)-
	echo "ss: "                    -$(ss)-
	echo "tax regime year: "       -$(yr)-
	echo "strategy: "              -$(strategy)-
	echo "strategy suffix: "       -$(strategy_suffix)-
	echo "strategy_year_suffix: "  -$(strategy_year_suffix)
	echo "user"                    -$(user)-


##=## ##=## ##=## ##=## ##=##
##=## the run-after-every-change test suite
##=## ##=## ##=## ##=## ##=##

# Sufficiently simple and fast tests can stay in the master "tests" recipe here.
# But for any test complex enough to require an output file,
# make that output file a dependency.
# PITFALL: purchase_input.txt always uses the full sample
tests:                                                      \
  users/$(user)/test/recip-1/rate_input.txt                 \
  users/$(user)/test/recip-1/requests.txt                   \
  users/$(user)/test/recip-$(ss)/households_1_agg_plus.txt  \
  users/$(user)/test/recip-$(ss)/households_2_purchases.txt \
  users/$(user)/test/recip-$(ss)/build_classes.txt          \
  users/$(user)/test/recip-$(ss)/build_purchases_2_vat.txt  \
  users/$(user)/test/recip-$(ss)/build_purchase_sums.txt    \
  users/$(user)/test/recip-1/build_ss_functions.txt         \
  users/$(user)/test/recip-1/build_ss_schedules.txt         \
  users/$(user)/test/recip-$(ss)/people_3_income_taxish.txt \
  users/$(user)/test/recip-$(ss)/people_4_post_households.txt \
  users/$(user)/test/recip-$(ss)/common_misc.txt            \
  users/$(user)/test/recip-$(ss)/common_util.txt            \
  users/$(user)/test/recip-$(ss)/people_main.txt            \
  users/$(user)/test/recip-$(ss)/people_2_buildings.txt     \
  users/$(user)/test/recip-$(ss)/purchases_correct.txt      \
  users/$(user)/test/recip-1/regime_r2018.txt               \
  users/$(user)/test/recip-$(ss)/vat_rates.txt              \
  users/$(user)/test/recip-1/build_buildings.txt            \
  users/$(user)/test/recip-1/purchase_inputs.txt
	printf '\nAll tests passed.\n\n'

# TODO: Replace this phony target with evidence that the test succeeded,
# so thaht it won't rerun unnecessarily.
users/$(user)/test/recip-1/rate_input.txt: \
  .no_younger_than/python/build/rate_input_test.py
	$(python_from_here) python/build/rate_input_test.py $(config_file)

users/$(user)/test/recip-1/requests.txt: \
  .no_younger_than/python/requests/test.py
	date
	$(python_from_here) python/requests/test.py $(config_file)

users/$(user)/test/recip-$(ss)/households_1_agg_plus.txt:                 \
  $(households_1_agg_plus)                                         \
  .no_younger_than/python/build/households_1_agg_plus_test.py
	date
	$(python_from_here) python/build/households_1_agg_plus_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/households_2_purchases.txt:                 \
  $(households_2_purchases)                                         \
  .no_younger_than/python/build/households_2_purchases_test.py
	date
	$(python_from_here) python/build/households_2_purchases_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/build_classes.txt:           \
  .no_younger_than/python/build/classes_test.py
	date
	$(python_from_here) python/build/classes_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/common_misc.txt:           \
  .no_younger_than/python/common/misc_test.py
	date
	$(python_from_here) python/common/misc_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/common_util.txt:           \
  .no_younger_than/python/common/util_test.py
	date
	$(python_from_here) python/common/util_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/purchases_correct.txt:                 \
  $(purchases_1)                                               \
  .no_younger_than/python/build/purchases/correct_test.py
	date
	$(python_from_here) python/build/purchases/correct_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/build_purchases_2_vat.txt:           \
  $(purchases_2_vat)                                         \
  .no_younger_than/python/build/purchases_2_vat.py
	date
	$(python_from_here) python/build/purchases_2_vat_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/build_purchase_sums.txt:           \
  $(purchase_sums)                                         \
  .no_younger_than/python/build/purchase_sums_test.py
	date
	$(python_from_here) python/build/purchase_sums_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/people_main.txt:                 \
  $(people_1)                                            \
  .no_younger_than/python/build/people/main_test.py
	date
	$(python_from_here) python/build/people/main_test.py \
          $(config_file)

# PITFALL: for buildings.csv we always use subsample=1.
users/$(user)/test/recip-1/build_buildings.txt:               \
  $(buildings)                                         \
  .no_younger_than/python/build/buildings_test.py
	date
	$(python_from_here) python/build/buildings_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/people_2_buildings.txt:                 \
  $(people_1)                                                   \
  $(people_2_buildings)                                         \
  .no_younger_than/python/build/people_2_buildings_test.py
	date
	$(python_from_here) python/build/people_2_buildings_test.py \
          $(config_file)

# TODO: Currently 2018 is tested, regardless of the actual regime-year.
# It would be better to have separate tests for each year.
users/$(user)/test/recip-1/regime_r2018.txt:               \
  .no_younger_than/python/regime/r2018_test.py
	date
	$(python_from_here) python/regime/r2018_test.py \
          $(config_file)

users/$(user)/test/recip-1/build_ss_functions.txt:            \
  .no_younger_than/python/build/ss/functions_test.py
	date
	$(python_from_here) python/build/ss/functions_test.py \
          $(config_file)

users/$(user)/test/recip-1/build_ss_schedules.txt:            \
  .no_younger_than/python/build/ss/schedules_test.py
	date
	$(python_from_here) python/build/ss/schedules_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/people_3_income_taxish.txt:   \
  $(people_3_income_taxish)                           \
  .no_younger_than/python/build/people_3_income_taxish_test.py
	date
	$(python_from_here)                               \
          python/build/people_3_income_taxish_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/people_4_post_households.txt:  \
  $(people_4_post_households)				      \
  $(people_3_income_taxish)				      \
  $(households_2_purchases)				      \
  .no_younger_than/python/build/people_4_post_households_test.py
	date
	$(python_from_here)				      \
          python/build/people_4_post_households_test.py	      \
          $(config_file)

# PITFALL: Sample size is hardcoded to 1, because otherwise
# certain rare values would never be encountered.
users/$(user)/test/recip-1/purchase_inputs.txt:                     \
  $(input_subsamples)                                        \
  .no_younger_than/python/build/purchases/input_test.py
	date
	$(python_from_here) python/build/purchases/input_test.py \
          $(config_file)

users/$(user)/test/recip-$(ss)/vat_rates.txt:                 \
  $(vat_rates.py)                                      \
  .no_younger_than/python/build/vat_rates_test.py
	$(python_from_here) python/build/vat_rates_test.py \
          $(config_file)
