import pandas as pd
import os

def saveStage(subsample,data,name):
  path = 'output/vat-data/recip-' + str(subsample)
  if not os.path.exists(path): os.makedirs(path)
  data.to_csv( path + '/' + name + ".csv" )

def readStage(subsample,name): # to skip rebuilding something
  path = 'output/vat-data/recip-' + str(subsample)
  return pd.read_csv( path + '/' + name + ".csv" )


# Commonly used (copy, paste) commands to read into Python's working memory the data generated by build.py

if False:
  subsample = 1
  
  purchasesEarly = readStage( subsample, '/1.purchases') # memory hog
  purchases = readStage( subsample, '/2.purchases,prices,taxes') # memory hog
  
  demog = readStage( subsample, '/4.demog')
  people = readStage( subsample, '/5.person-demog-expenditures')
  households = readStage( subsample, '/6.households')
