* PITFALL: These notes files are redundant
There's an enig.org file, an enph.org file, and this one which pertains to both.
* PITFALL: These notes are stale, from 2018-ish
But they might include some insights into the data due to David Suarez not recorded elsewhere.
* to do
** interpreting frequencies
*** problem: 2.1 or 2?
*** problem: 9 = how infrequent?
**** As a frequency code, 9 usually means "sporadically". I thought that meant "less frequently than every year", assuming that the terms are ordered. But over here it interprets 9 as "Esporádica por semana".
**** links
** Match the covering vocabularies to the COICOP items.
This can be done for all of 2017, and for 2007 goods, but for 2007 services the COICOP data uses an obsolete coding.
** are these more expenditure data sets?
*** sea_enc_gcar_csv
**** NC2_CC_P2
1 » 2. Diario
2 » 2.1. Varias veces por semana
3 » 3. Semanal
4 » 4. Quincenal
5 » 5. Mensual
6 » 6. Bimestral
7 » 7. Trimestral
9 » 9. Esporádica"
*** sea_enc_gcau_csv
**** NC2_CC_P2
1 » 1. Nunca
2 » 2. Diario
3 » 2.1 varias veces por semana
4 » 3. Semanal
5 » 4. Quincenal
6 » 5. Mensual
7 » 6. Bimestral
8 » 7. Trimestral
9 » 9. Esporádica"
ss frequently than every year", assuming that the terms are ordered. But over here it interprets 9 as "Esporádica por semana".
* references
tax.co/hopefully-obsolete/enig-enph,email,david-suarez,2018-02-23.md
