* SS contrib's
** refs
"rentas naturales.xlsx"
the tax code
  https://www.dian.gov.co/atencionciudadano/formulariosinstructivos/Formularios/2018/Formulario_210_2018.pdf
** algorithm
There are three kinds of SS contribs, and two kinds of employee (salaried and contractor). Both pay all three if they make enough money. Salaried employees' employers contribute some also. The rates change at certain thresholds. The tax rate for SS contrib's is tax / income for contractors, and tax / (employer burden = income + employer contrib's) for employees.
** defs
parafiscales = only for asalariados, and paid only by the employer
  and only for employees who earn more than 10 minimum wages

salario integral: where they just give you more money because you're making so much money. specifically 13 min wages. Here the employer expects you to pay your "prestaciones sociales", rather than the employer paying them. Prestaciones sociales = cesantias, "interest" (12% more) on cesantias, and prima de servicios = the biannual half-a-month's salary bonus.
** two worked examples
*** making 10 min wages
  before getting paid, the following is taken from that:
    4% for pension
    4% for health
    1% solidaridad
  also, his employer puts in:
    12% of that goes to pension
    8.5 salud
    5 parafiscales
    4 cajas
    something (?) for cesantias -- pretend it's 30% although it looks like 17.7
*** making 20 minimum wages, salario integral
  the employee, by law, must contribute from that:
    a few might avoid these, but surely small
    4% of 70% of that for pension
    same with salud, 4% of 70%: mandatory
      "UGPP" enforces this
    same with solidaridad: 2% (at that income level) of .7, UGPP-enforced
  employer puts in, as well:
    .12 of .7 for pension
    .085 of .7 for health
    .05 of .7 for parafiscal
    .04 of .7 for cajas
    nothing to prestaciones sociales
      = cesantias, interest on cesantias, biannual bonus ("prima de servicios")
* labor & pension(receipt) income
** there's a table image (.png or something) in the spreadsheet that gives marginal tax rates as a function of income. But subtract exemptions and deductions first, in the order eblow.
** in the sheet "trabajo & pensiones"
*** the algorithm
Skip case 1, it's unrealistc.
The only thing changing row by row is the marginal tax rate.
We apply deductions and exemptions first, then marginal-tax the rest.
*** the (modelable from enph) deductions
**** (1) (First): subtract mandatory part of SS contrib's
ENPH data on this is garbage; instead, simulate from the total labor income.
Compute this ala SS contrib spreadsheet.
**** (2) If dependents, subtract 10% from income
Complicated.
Hack: Anyone in house who doesn't work.
**** interest payments on a mortgage
*** the (modelable from enph) exemptions
**** gastos de representacion
**** cesantias (receipts)
**** (last): subtract 25% of what remains of your labor income
*** TODO (david) wrinkle: need a min and max total of other deductions|exemptions, as a function of individual income
