* SS contrib's
David sent me a spreadsheet and walked me through social security contributions on it.
There are three kinds of SS contribs, and two kinds of employee (salaried and contractor). Both pay all three if they make enough money. Salaried employees' employers contribute some also. The rates change at certain thresholds. The tax rate for SS contrib's is tax / income for contractors, and tax / (employer burden = income + employer contrib's) for employees.
* labor & pension(receipt) income
** might not need
*** mínimo para declarar (por income): if you make this much you must declare, but still might not pay
*** mínimo para declarar por patrimonio: patrimonio = weatlh. must declare if either implies must declare.
** there's a table image (.png or something) in the spreadsheet that gives marginal tax rates as a function of income. But subtract exemptions and deductions first, in the order eblow.
** in the sheet "trabajo & pensiones"
*** the algorithm
Skip case 1, it's unrealistc.
The only thing changing row by row is the marginal tax rate.
We apply deductions and exemptions first, then marginal-tax the rest.
*** the (modelable from enph) deductions
**** (1) (First): subtract mandatory part of SS contrib's
ENPH data on this is garbage; instead, simulate from the total labor income.
Compute this ala SS contrib spreadsheet.
**** (2) If dependents, subtract 10% from income
Complicated.
Hack: Anyone in house who doesn't work.
**** interest payments on a mortgage
*** the (modelable from enph) exemptions
**** gastos de representacion
**** cesantias (receipts)
**** (last): subtract 25% of what remains of your labor income
