* TODO email 2018 09 27
*** TODO P6050 = "unidad de gasto"
 If equal to 6,7, or 8, kind of part of the household but not really?
 If I want to know what a household spent, I should exclude persons marked 6-8?
 Will the expenditures of a person marked 6-8 be recorded in the household in which they are (say) a maid, or in a different household, or in no household?
*** exmployment status
 p6430 - the kinds of employment. 1-3 = asalriado, 4-5 = independent (business owner + contractor), Jornalero/peon = someone working someone else's land, informally, maybe paid in money or in kind but no contract, not considered asalariado.
*** P6500-P6640S1 : Info for asalariados
  not contractors, not business owners. The basis for all the "overlook" questions is p6500 (labor income). The survey includes in-kind payments.
 DIAN counts in-kind payments as income for tax purposes, so we'd better.
 "Subsidio" in this context can mean something given by the employer, not nec'y the gov't.
 The in-kind payments are never included in P6500, so there are no "did you include this in that" questions for those.
 Questions P6630S1-P6630S6A1 refer to the last twelve months, not the last month. So divide by 12 and add to p6500
*** p6765-P1651S1 : Info for "independientes"   
 = (self-employed, temporary workers, contractors). That classification as "independientes" is obtained from answers to question P6430-options 4 and 5. Option g for P6765 implies the filling of an extra form (“modulo de negocios”: info is relevant for small businesses in activities related to commerce, industry, and services).
 P6750 = main income question. Must divide by P676, # of months.
 p550 = something to add after dividing by 12 if it exists.
 TODO - Does P6750 include P6779S1, or should we add it?
 TODO - Does P6750 already reduced by P1651S1, or should we subtract it?
     That's an insurance paid by the contractor in case of non-fulfillment.
*** P6790-P9450S1: Info for both asalariados and independientes: for instance, questions about pension contributions, frequency of wage payments, among others.
 Could use P6800 or P6850 to get hours.
 P6920S1 = pension contributions
 P6940's option C is legally impossible.
 For each of these 4 cases:
    Asalariado & paying all of it
    Asalariado & paying some, the employer the rest
    Independent & paying nothing
    Independent & paying all of it
 suppose the employer spends 10 on the employee, and 1 goes to pensions. What will questions P6920S1 and the main income question (P6500 or P6750) say? Same for P6990S1, P9450S1
*** P7040-p7070: Info about second job. Very general info about additional jobs.
 P7070 = main income at that second job. No overlap with the previous main income question
*** p7310-P7472S1: Info for unemployed and inactives  
 P9460 = unemployment income. Taxed as income?
 P7422(S1) correspond to labor income earned in last month for people that are classified as unemployed according to the survey. "Inactive" is different.
 p7472 : labor income earned in last month for people that are classified as inactivos (students, retired, unpaid domestic) according to the survey. The classification as inactive or unemployed comes from the module for labor force (questions p6240 to p6350).
*** P7500S1 - P7500S5A1 : rental income
*** P7500S2 - P7510S4A1 : benefits income
*** P7510S5(A1), P7510S10*, P7510S9* : investment income
*** P7510S6 : "cesantias" = for each year of work, a month of salary, paid after leaving
*** P1668S1 - P1668S6: other benefits
*** P7513S1 - P7513S12A1 : infrequent earnings : sale, lottery, ...
**** these seem to overlap:
 P7510S9 = "rendimientos por venta de titulos"
 P7513S4 = "Ventas de acciones y de títulos valores"
**** these seem to overlap:
 P7513S5 = "Reembolsoso de dinero prestado por usted o a otra persona"
 P7513S7A1 = " Préstamos particulares"
*** P7513S8 = jury awards

* TODO next
** TODO next: add region, estrato (see below)
** frequency
*** remap urban cap c to match the others
*** once it's interpretable, add it to the capitulo c legend code
** value = expense; price = value / quantity
*** David used real data, e.g. rice price, to figure this out. Genius.
** where-bought: search for "no vat" in enph.org
** how-got: see enph.org
** kinds of income
*** labor
*** investment, business income
*** transfer : from gov't or charity or family or alimony
* to explain in paper : institution details | judgment calls
** terms in the ENPH
*** Unemployed
During the past four weeks, actively searching for a job and available last week to start in case of success; or employed at least 2 weeks over the last 12 months, has actively searched after last job and was available last week to start in case of success; or not employed at least 2 weeks over the last 12 months, has actively searched after last job and was available last week to start in case of success.
*** Inactive 
Permanent disability; or During the past four weeks, actively searching for a job and not available last week to start in case of success; or not willing to work; or full-time students; or employed at least 2 weeks over the last 12 months but has not actively searched after last job; or full time domestic work; or has not searched for a job during the past 12 months; or has searched a job over the last 12 months but was not available to start last week in case of success.
** they are asked on the 15th about consumption on days 1-14
** where-got: if missing, assume taxed
# Even when purhcase=1, in some files there are a substantial number
# of observations where where-got is missing. A way to see that:
util.dwmByGroup( "file-origin",
                 data.purchases[ data.purchases["is-purchase"]==1 ]
                 [["file-origin","where-got"]] )
** freq: if missing, discarded
*** when is-purchase=1, freq is undefined only .015 % of the time
*** so omitting purchase!=1 observations won't bias our estimate of VAT
*** it will, however, bias (downward) our estimate of consumption
** we don't include property purchases
*** there is no VAT on land purchases
*** there is 5% VAT for purchases of *new* homes in excess of 880 M pesos
**** but the data only reports newness in the case of second homes
**** that's a very small fraction of the economy
** more than 2/3 of the "capitulo c" observations have no associated value
*** and they are only divided into 25 broad categories, with no associated quantity variable, so imputation is infeasible
*** Those value-missing observations are 19.2% of our data.
* would be nice
** to have a default value for freq
*** when is-purchase=1, freq is undefined only .015 % of the time
*** so omitting purchase!=1 observations won't bias our estimate of VAT
*** it will, however, bias (downward) our estimate of consumption
* about the data|results
** The ENPH : http://microdatos.dane.gov.co/index.php/catalog/566/get_microdata
** the 200 / 1400 missing COICOP codes appear not to matter much
*** the 80% of purchases that carry 0 VAT are due to a literally 0 VAT, not a NaN VAT
*** in the 10% sample less than 0.3% of the purchases have a NaN vat rate
x = purchases["vat-rate"]
>>> len(x)
7458243
>>> len( x[ x.isnull() ] )
28986
>>> 28986 / 7458243
0.0038864381329490067
* restaurant|cafeteria tax / todo
** if bought in cafeteria or restaurant, gets the 8% tax and no VAT, but otherwise they would pay VAT
* income tax / todo
** ENPH asks about income tax
** if no SS payments and (or?) making less than min wage, informal
** primary inputs: income, kids, voluntary pension fund contributions.
** at most 40% of a person's inncome can be exempt.
* VAT / todo
** code-internal
*** pdflatex: send reports to a file, not stdout
**** this way it doesn't drown the python error reports
** check data
*** TODO what are the biggest expenditures in the zero-vat set? good to check those vat rates.
*** is it half of households or half of individuals who have no income?
*** is it missing sole proprietor income?
**** is the income data equally missing in the GEIH?
** add features
*** household VAT rates by income decile
*** regional VAT rates
>>> df[ "joined" ] = df[ "DOMINIO" ] + " + " + df["REGION"]
>>> for c in sorted( df[ "joined" ].unique() ): print(c)

centro poblado = smallest unit
otras cabeceras = bigger, aggregate of municipalities
bigger yet are cities, which are identified by name
rural disperso = by area biggest, but low population (and low density)

Luis wanted at least for ...
  - Bogota
  - Medellín
  - Cali
  - Barranquilla+Soledad (one metro area)
  - Bucaramanga
  - Cartagena
  - Cúcuta
  - Ibagué
  - Pasto
  - Popayán
*** ? include people/spending (already drawn)
*** make x-ticks more readable on some figures (e.g. fig 7, people/income)
*** TODO every spendinng graph, draw for people even with zero income
*** TODO CDF / spending: draw that for every income decile
*** TODO do things by estrato; assume someone's electrical estrato is their estrato
***** P8520S1A1
*** if we had VAT as a function of estrato, then we could
**** apply those rates to income data from a survey with more incomme data
